import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CopilotKit runtimeUrl="/api/copilotkit/amis" agent="AmisEditorPageAgent">
      {children}
    </CopilotKit>
  );
}
